### ISSUE TITLE
Add maskable icon to manifest

### ISSUE THREAD

**Issue by johannes-bittner** [Kuestenschmiede/PwaBundle#11]
Lighthouse beschwert sich, dass das Manifest keine Angaben zu einem maskable icon enthält: 

![grafik](https://user-images.githubusercontent.com/1597697/93490179-710db600-f908-11ea-87ae-3e99126df367.png)

Das lässt sich zwar händisch in der manifest.json einfach nachrüsten, dürfte dort aber vermutlich nicht updatesicher sein: 
`		{
			"src": "/path/to/maskable_icon.png",
			"sizes": "640x640",
			"type": "image/png",
			"purpose": "any maskable"
		}`

**Comment by coastforge-mei** [comment]
Das maskable icon kann mit der neuen Version (2.1.0) in der Konfiguration gesetzt werden.
