### ISSUE TITLE
Add default Template for AddManifestModule

### ISSUE THREAD

**Issue by doishub** [Kuestenschmiede/PwaBundle#14]
Hallo,

in einer unserer [Erweiterungen](https://github.com/oveleon/contao-cookiebar) verwenden wir den Hook `parseFrontendTemplate`.  In Verbindung mit dieser Erweiterung, scheint es nach dem Hinzufügen des Manifest-Moduls im Layout einen Fehler zu geben:

```
Argument 2 passed to Oveleon\ContaoCookiebar\EventListener\FrontendTemplateListener::onParseFrontendTemplate() must be of the type string, null given, called in E:\Projekte\Testumgebungen\contao49\vendor\contao\core-bundle\src\Resources\contao\classes\FrontendTemplate.php on line 51
```

Es scheint als würde hier ein Standard-Template im Modul `AddManifestModule` fehlen. Laut [Doku](https://docs.contao.org/dev/reference/hooks/parseFrontendTemplate/) sollte dieser Wert zumindest nicht `null` sein können.

Da ich keine Erfahrung mit dieser Erweiterung habe, möchte ich ein Konfigurationsfehler nicht ausschließen.

**Ursprüngliches Issue:**
https://github.com/oveleon/contao-cookiebar/issues/48

**Version:**
v2.1.0

**Comment by coastforge-cro** [comment]
Hallo doishub,

danke für die Meldung. Wir haben jetzt ein Template für das Manifest-Modul eingebaut, dadurch tritt der Fehler in Verbindung mit der Verwendung des Hooks nicht mehr auf. Dieser Fix ist im neuen Bugfix-Release 2.1.1 enthalten.
