### ISSUE TITLE
Backend send push notification broken in debug mode

### ISSUE THREAD

**Issue by dmolineus** [Kuestenschmiede/PwaBundle#2]
When using send push in backend debug mode I get a 500 error. Tested with Contao 4.8.

![2019-09-12 16 44 05 localhost 17813bbd2106](https://user-images.githubusercontent.com/1186266/64794461-d2c07500-d57c-11e9-9acb-b6ac0e96a02d.png)

**Comment by coastforge-cro** [comment]
Thanks, I fixed this in the v1.6.2 release.
