### ISSUE TITLE
Add inserttag support - "additional URLs"

### ISSUE THREAD

**Issue by derkosmonaut** [Kuestenschmiede/PwaBundle#29]
It would be great if you could store an insert tag with {{file::xxxx}} in the "Additional URLs" field to better cache assets, for example. 
Our usecase is the following: we are developing a kind of tour app whose content is provided via a catalog. These are mp3s, images etc. We can automatically generate a file, which summarizes a list of all assets of a starting point. This list could be automatically transferred to the manifest via inserttag.

**Comment by coastforge-mei** [comment]
Good idea. We'll try to integrate the tag in the next few days.

**Comment by coastforge-mei** [comment]
With version 2.5.0, insert tags are now possible.
