### ISSUE TITLE
Feature / Brain Storming: Offline Forms

### ISSUE THREAD

**Issue by amenk** [Kuestenschmiede/PwaBundle#3]
Wäre es möglich Offline Forms zu integrieren, welche man ohne Verbindung abschicken kann und welche dann später hochgeladen werden?

**Comment by coastforge-mei** [comment]
Technisch wäre sicherlich etwas machbar. Die Frage ist, ob das ins PWA-Bundle gehört? Man müsste die Daten beim Versenden (nur im Offline-Fall) im LocalStorage zwischenspeichern und absenden sobald die Verbindung wieder da ist. Das kann ja grundsätzlich für Webseiten sinnvoll sein.
