### ISSUE TITLE
Contao 5.1.x and PWA-Bundle

### ISSUE THREAD

**Issue by sdahlmann** [Kuestenschmiede/PwaBundle#30]
Frage: Wird es für die Contao-Erweiterung "PWA-Bundle" in Absehbarer Zeit einen Fix für Contao 5.1.x geben? Ich würde mich sehr darüber freuen.

Question: Will there be a fix for Contao 5.1.x for the Contao extension "PWA-Bundle" in the above future? I would be very happy about it.

**Comment by coastforge-mei** [comment]
Wir möchten alle unsere Erweiterungen in nächster Zeit für Contao 5 anpassen. Da Contao 5 noch keine LTS-Version erreicht hat, hat das für unsere Projekte aktuell noch keine hohe Prio. Da wir aber in Kürze eine neue Version machen wollen, werden wir auf jeden Fall prüfen, was an Aufwand auf uns zu kommt. Ggf. ist es keine große Sache und es fließt direkt mit ein. Das PWA Bundle hat den Vorteil, dass es keine Abhängigkeiten zu anderen Contao-Erweiterungen hat.

**Comment by coastforge-mei** [comment]
Die Version 2.5 läuft jetzt unter Contao 5. Es sind aber noch nicht alle Funktionen getestet. Wir bleiben am Ball.

**Comment by sdahlmann** [comment]
Ich kann Ihre PWA-Erweiterung leider nicht unter Contao 5.3.4 LTS installieren. Mit früheren Contao 5.x Versionen hat es noch einwandfrei funktioniert, wofür ich mich auch bedanken möchte bezüglich der Contao 5.x Anpassung. Der Contao Manager gibt mir folgende Fehlermeldung aus:

> Resolving dependencies using Composer Cloud v3.7.0
[6.9MiB/0.22s] Loading composer repositories with package information
[69.3MiB/10.03s] Updating dependencies
[88.2MiB/10.36s] Your requirements could not be resolved to an installable set of packages.
[88.2MiB/10.37s] 
  Problem 1
    - con4gis/pwa[v2.5.0, ..., v2.5.7] require doctrine/persistence ^2.3.0 -> satisfiable by doctrine/persistence[2.3.0, ..., 2.5.7].
    - You can only install one version of a package, so only one of these can be installed: doctrine/persistence[1.3.0, ..., 1.3.8, 2.0.0, ..., 2.5.7, 3.0.0, ..., 3.3.2].
    - contao/core-bundle[5.3.2, ..., 5.3.4] require doctrine/persistence ^3.2 -> satisfiable by doctrine/persistence[3.2.0, 3.3.0, 3.3.1, 3.3.2].
    - contao/calendar-bundle 5.3.4 requires contao/core-bundle 5.3.4 -> satisfiable by contao/core-bundle[5.3.4].
    - contao/calendar-bundle is locked to version 5.3.4 and an update of this package was not requested.
    - Root composer.json requires con4gis/pwa ^2.5 -> satisfiable by con4gis/pwa[v2.5.0, ..., v2.5.7].

Frage: Können Sie das Problem bitte bei Gelegenheit beheben? Es sind keine Weiteren Erweiterungen installiert zum Zeitpunkt des Versuchs. Contao lief unter PHP 8.2. Ich bedanke mich dafür schon im Voraus bei Ihnen.

**Comment by sdahlmann** [comment]
Update Fehlermeldung unter Contao 5.3.13 LTS und PHP 8.3:
> Resolving dependencies using Composer Cloud v3.7.1
[7.0MiB/0.20s] Loading composer repositories with package information
[70.9MiB/8.80s] Updating dependencies
[90.2MiB/9.03s] Your requirements could not be resolved to an installable set of packages.
[90.2MiB/9.04s] 
  Problem 1
    - con4gis/pwa[v2.5.0, ..., v2.5.9] require doctrine/persistence ^2.3.0 -> satisfiable by doctrine/persistence[2.3.0, ..., 2.5.7].
    - You can only install one version of a package, so only one of these can be installed: doctrine/persistence[1.3.0, ..., 1.3.8, 2.0.0, ..., 2.5.7, 3.0.0, ..., 3.3.3].
    - contao/core-bundle 5.3.13 requires doctrine/persistence ^3.2 -> satisfiable by doctrine/persistence[3.2.0, ..., 3.3.3].
    - alpdesk/alpdesk-parallax 1.2.0 requires contao/core-bundle ^4.13 || ^5.0 -> satisfiable by contao/core-bundle[4.13.0, ..., 4.13.47, 5.0.0, ..., 5.4.1].
    - alpdesk/alpdesk-parallax is locked to version 1.2.0 and an update of this package was not requested.
    - Root composer.json requires con4gis/pwa ^2.5 -> satisfiable by con4gis/pwa[v2.5.0, ..., v2.5.9].
[90.2MiB/9.04s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[41.2MiB/9.07s] Memory usage: 41.21MB (peak: 198.62MB), time: 9.08s.
[41.2MiB/9.08s] Finished Composer Cloud resolving.
# Cloud Job ID PpQL6TEH4JL0UEPBrk4wYZVCDtFIaKynoKqLNLSy0fpb798fxIXS3cdxxAvR3Emb1Ku66nRSvdcR9dT failed

**Comment by sdahlmann** [comment]
Update Fehlermeldung unter Contao 5.3.13 LTS und PHP 8.3:

Resolving dependencies using Composer Cloud v3.7.1
[7.0MiB/0.20s] Loading composer repositories with package information
[70.9MiB/8.80s] Updating dependencies
[90.2MiB/9.03s] Your requirements could not be resolved to an installable set of packages.
[90.2MiB/9.04s]
Problem 1
- con4gis/pwa[v2.5.0, ..., v2.5.9] require doctrine/persistence ^2.3.0 -> satisfiable by doctrine/persistence[2.3.0, ..., 2.5.7].
- You can only install one version of a package, so only one of these can be installed: doctrine/persistence[1.3.0, ..., 1.3.8, 2.0.0, ..., 2.5.7, 3.0.0, ..., 3.3.3].
- contao/core-bundle 5.3.13 requires doctrine/persistence ^3.2 -> satisfiable by doctrine/persistence[3.2.0, ..., 3.3.3].
- alpdesk/alpdesk-parallax 1.2.0 requires contao/core-bundle ^4.13 || ^5.0 -> satisfiable by contao/core-bundle[4.13.0, ..., 4.13.47, 5.0.0, ..., 5.4.1].
- alpdesk/alpdesk-parallax is locked to version 1.2.0 and an update of this package was not requested.
- Root composer.json requires con4gis/pwa ^2.5 -> satisfiable by con4gis/pwa[v2.5.0, ..., v2.5.9].
[90.2MiB/9.04s] Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
[41.2MiB/9.07s] Memory usage: 41.21MB (peak: 198.62MB), time: 9.08s.
[41.2MiB/9.08s] Finished Composer Cloud resolving.
Cloud Job ID PpQL6TEH4JL0UEPBrk4wYZVCDtFIaKynoKqLNLSy0fpb798fxIXS3cdxxAvR3Emb1Ku66nRSvdcR9dT failed

**Comment by coastforge-mei** [comment]
Thanks for the message. Please test again with version 2.6
