### ISSUE TITLE
Installation in Contao 5.3.18 schlägt fehl

### ISSUE THREAD

**Issue by johannes-bittner** [Kuestenschmiede/PwaBundle#37]
Ich versuche gerade, im Rahmen eines Updates das PwaBundle in einer Contao 5.3.18 zu installieren (PHP 8.2/8.3), erhalte aber die Fehlermeldung: 

>   Problem 1
>     - con4gis/pwa[v2.5.0, ..., v2.5.9] require doctrine/persistence ^2.3.0 -> satisfiable by doctrine/persistence[2.3.0, ..., 2.5.7].
>     - You can only install one version of a package, so only one of these can be installed: doctrine/persistence[v1.0.0, ..., 1.3.8, 2.0.0, ..., 2.5.7, 3.0.0, ..., 3.4.0].
>     - contao/core-bundle 5.3.18 requires doctrine/persistence ^3.2 -> satisfiable by doctrine/persistence[3.2.0, ..., 3.4.0].
>     - contao/manager-bundle 5.3.18 requires contao/core-bundle 5.3.18 -> satisfiable by contao/core-bundle[5.3.18].
>     - con4gis/pwa[v1.0.0, ..., v1.6.3, v2.0.0, ..., v2.3.2] require contao/core-bundle ^4.4 -> found contao/core-bundle[4.4.0, ..., 4.13.50] but these were not loaded, likely because it conflicts with another require.
>     - con4gis/pwa[v2.1.0, ..., v2.4.2] require contao/core-bundle ^4.9 -> found contao/core-bundle[4.9.0, ..., 4.13.50] but these were not loaded, likely because it conflicts with another require.
>     - contao/manager-bundle is locked to version 5.3.18 and an update of this package was not requested.
>     - Root composer.json requires con4gis/pwa * -> satisfiable by con4gis/pwa[v1.0.0, ..., v1.6.3, v2.0.0, ..., v2.5.9].

Ist ja im Manager zwar als installierbar angezeigt - aber offensichtlich hängt das an den unterschiedlichen Versionen von doctrine/persistence (^3.2 vs. ^2.3.0). 

Lässt sich das kompatibel machen?

**Comment by coastforge-mei** [comment]
Danke für die Meldung. Bitte teste erneut mit der Version 2.6.
