### ISSUE TITLE
When putting Manifest Module into a page, Fatal error, because strTemplate is null

### ISSUE THREAD

**Issue by amenk** [Kuestenschmiede/PwaBundle#4]
I am getting this error as soon as I put the module into a page

    Argument 2 passed to ContaoBootstrap\Core\Listener\TemplateParseListener::parse() must be of the type string, null given, called in workspace/pwacontao/vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php on line 52

If I replace the line in the core code

				$strBuffer = $this->{$callback[0]}->{$callback[1]}($strBuffer, $this->strTemplate);

with

				$strBuffer = $this->{$callback[0]}->{$callback[1]}($strBuffer, $this->strTemplate ?? '');

it works.

Is that a problem of PwaBundle as the manifest module does not have a template field or a another problem?

**Comment by coastforge-mei** [comment]
No own template is created in the module. For us the error does not occur at all. Which Contao and pwa version do you use?

**Comment by amenk** [comment]
I think, the reason that there is no template, might be the problem... but I have no clue, to be honest

contao/core-bundle                         4.8.5             
con4gis/pwa v1.6.2
contao-themes-net/mate-theme-bundle        2.3.1
