### ISSUE TITLE
redirect pages should never be cached

### ISSUE THREAD

**Issue by amenk** [Kuestenschmiede/PwaBundle#5]
The service worker seems to cache all the pages on installation, which is fine.

But when there is external redirect (I am testing with the mate theme which redirects to an exernal website), I get

    Cross-Origin Read Blocking (CORB) blocked cross-origin response https://meissen.online/ with MIME type text/html.

So I think external redirects always should be excluded from the caching.

**Comment by coastforge-mei** [comment]
In any case, it makes sense that the app does not cache the external content. We will try to disable this in general.

**Comment by coastforge-mei** [comment]
fixed >= 2.0
