### ISSUE TITLE
app/config/config.yml is not used when config/config.yml exists

### ISSUE THREAD

**Issue by MaksimDonic** [Kuestenschmiede/PwaBundle#6]
Contao version: 4.8.5
Con4gis-PWA version: 1.6.2

If I change the configuration of JSON Manifest, it will be always **app/config/config.yml** generated. 

In Contao 4.8 there can be a config.yml in **config/** on root level.
If that file exist, the configuration from **app/config/config.yml** is not used.

The Bundle should probably check, if there is a config.yml in config folder and use that file, instead of creating a new one in app/config folder.

**Comment by coastforge-cro** [comment]
Thanks for your hint. You are right, we will add a check to be compatible with both paths in the next version.

**Comment by coastforge-cro** [comment]
Fixed in 1.6.3.
